CREATE TABLE IF NOT EXISTS item (
    id INT(11) UNSIGNED AUTO_INCREMENT,
    link VARCHAR(255) NOT NULL DEFAULT "",
    title VARCHAR(255) NOT NULL DEFAULT "",
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY link_uniq (link)
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;
